### ISSUE TITLE
Doesn't work with Composer-Redactor

### ISSUE THREAD

**Issue by kengher** [julianlam/nodebb-plugin-audio-embed#10]
This plugin seem to only work for Composer-default and Markdown.
When using Composer-Redactor (with markdown disabled) I get this error:

`
main.js:50 Uncaught ReferenceError: templates is not defined
    at main.js:50
`

Line: 50 
`
templates.parse('partials/audio-embed', {
`

**Comment by julianlam** [comment]
Can you check compatibility with the quill composer instead?

**Comment by kengher** [comment]
I checked. No javascript errors with quil, but it just appended a text link into the composer instead of a player.  Tested on both 1.17.1 & 1.17.2.
I have not yet checked with all other plugins disabled to confirm if there are conflicts.

**Comment by julianlam** [comment]
:point_up: probably fixes Redactor, although we don't technically support it anymore. I'll look into Quill integration.

**Comment by julianlam** [comment]
![image](https://user-images.githubusercontent.com/923011/126835069-5d01726c-13f1-45fa-862d-c6395e030d95.png)

Confirming audio embed works fine in Quill. It doesn't embed the actual player into the quill editor, but that's to be expected. `audio-embed` will convert the text string `[audio/blahblah]` into the player on-the-fly once the post is loaded.
