### ISSUE TITLE
Error code 413

### ISSUE THREAD

**Issue by Spacebody** [julianlam/nodebb-plugin-audio-embed#3]
While uploading mp3 files will return the result Error 413, so what happened?

**Comment by julianlam** [comment]
Are you using nginx or some other reverse proxy?

Also hey @pichalite this guy has the same avatar as you :laughing:

**Comment by Spacebody** [comment]
I use nginx.

**Comment by Spacebody** [comment]
Hah, interesting.

**Comment by Spacebody** [comment]
Fine, my team member had fixed this problem. I will closed this issue.
