### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by hariom282538** [julianlam/nodebb-plugin-audio-embed#4]
/assets/uploads/audio-embed/5gI7G1OwBDbDyn6Xt76RgDDe.mp3?v=ff3cjmucksu

**Comment by hariom282538** [comment]
Note: I checked on server there is no folder created inside uploads having name audio_embed , for debugging i found a folder whose location is ":/var/www/html/nodebb/var/www/html/nodebb/public/uploads/audio-embed"

**Comment by julianlam** [comment]
What OS are you running on?

**Comment by hariom282538** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04

**Comment by julianlam** [comment]
dc82d0e33d4909cf8bc71b31471a94a387cb85ac v1.1.0
