### ISSUE TITLE
Audio upload popup appears behind the default composer on mobile

### ISSUE THREAD

**Issue by FaizanZahid** [julianlam/nodebb-plugin-audio-embed#5]
So we are having issues uploading audio voice notes from mobile.

When we tap the audio upload icon, it doesn't appear above the composer, looks like it appears behind the composer, so when we finish the post and hit submit, the post gets added but the popup now appears to upload.

Looks like something to do with z index?

We r running all latest node bb 1.9.3 and latest ver of this plugin 1.1.3.

Please see image https://ibb.co/c1VY2d

**Comment by julianlam** [comment]
Closed via NodeBB/NodeBB#6532
